#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108242257-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.pro
# @License       : WTFPL
# @ReadME        : npx --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Tuesday, Aug 24, 2021 22:57 EDT
# @File          : npx
# @Description   : npx completion script
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_npx() {
  ___find() {
    find -L "$@" -type f -executable -printf "%f\n" 2>/dev/null
  }
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  local dir dirg dirn execs cur
  dir="$([[ -d "$(pwd -P 2>/dev/null)/node_modules/.bin" ]] && echo "$(pwd -P 2>/dev/null)/node_modules/.bin" || false)"
  dirg="$([[ -d "$(npm bin -g 2>/dev/null)" ]] && echo "$(npm bin -g 2>/dev/null)" || false)"
  dirn="${NODE_PATH//://*/node_modules/.bin/* }"
  execs=($(
    [[ -n "$dir" ]] && ___find $dir
    [[ -n "$dirg" ]] && ___find $dirg
    [[ -n "$dirn" ]] && ___find $dirn
  ))
  execs=("${execs[@]/#.\//}")
  cur=${COMP_WORDS[COMP_CWORD]}
  COMPREPLY=($(compgen -W "${execs[*]}" -- "$cur"))
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _npx npx
