#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108242257-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : WTFPL
# @ReadME        : npx --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Tuesday, Aug 24, 2021 22:57 EDT
# @File          : npx
# @Description   : npx completion script
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_npx() {
  ___find() { find -L $1 -type f -executable -printf "%f\n" 2>/dev/null; }
  local nodeDirs dir execs cur
  dir="$(pwd -P)"
  dirg="$(npm bin -g)"
  nodeDirs="$(echo "${NODE_PATH}" | tr ':' '\n')"
  while [[ -n "$dir" ]]; do
    if [[ -d "$dir/node_modules/.bin" ]]; then
      dir="$dir/node_modules/.bin"
      dir="${dir%/*}"
      continue
    fi
    [[ -n "$dir" ]] && dir="${dir:-} "
    [[ -n "$dirg" ]] && dir+="${dirg:-} "
    [[ -n "$NODE_PATH" ]] && dir+="${NODE_PATH//://*/node_modules/.bin/* }"
    execs=($(___find "$dir"))
    execs=("${execs[@]/#.\//}")
    cur=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=($(compgen -W "${execs[*]}" -- "$cur"))
    break
  done
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _npx npx
