#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108242257-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.pro
# @License       : WTFPL
# @ReadME        : setup_node --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Tuesday, Aug 24, 2021 22:57 EDT
# @File          : setup_node
# @Description   : setup_node completion script
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_setup_node() {
  local cur_word options
  local cur_word="${COMP_WORDS[$COMP_CWORD]}"
  local ARRAY="how2 emoj surge wikit vercel lessmd heroku eslint taskbook prettier vue "
  local ARRAY+="gitio-cli now-config speed-test angular auto-install readme-md-generator "
  local ARRAY+="npm-check-updates github-feed-cli"

  _init_completion || return
  if [[ "${cur_word}" == -* ]]; then
    COMPREPLY=($(compgen -W '--help --version --list' -- "${cur_word}"))
    return 0
  else
    COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur_word}"))
    return 0
  fi
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _setup_node setup_node
